import sys
import os
from operator import itemgetter
from typing import List, Dict, Any, Optional

from langchain_core.messages import BaseMessage
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_community.vectorstores import FAISS

from multi_doc_chat.utils.model_loader import ModelLoader
from multi_doc_chat.exception.custom_exception import DocumentPortalException
from multi_doc_chat.logger.custom_logger import CustomLogger
from multi_doc_chat.prompts.prompt_library import PROMPT_REGISTRY
from multi_doc_chat.model.models import PromptType, ChatAnswer
from pydantic import ValidationError

log = CustomLogger().get_logger(__name__)

class ConversationalRAG:
  """
  LCEL-based Conversational RAG with lazy retriever initialization
  """
  def __init__(self, session_id: Optional[str], retriever = None):
    try:
      self.session_id = session_id
      #Load LLM and prompts once
      self.llm = self._load_llm()
      self.contextualize_prompt: ChatPromptTemplate = PROMPT_REGISTRY[PromptType.CONTEXTUALIZE_QUESTION.value]
      self.qa_prompt: ChatPromptTemplate = PROMPT_REGISTRY[PromptType.CONTEXT_QA.value]
      #Lazy pieces
      self.retriever = retriever
      self.chain = None
      if self.retriever is not None:
        self._build_lcel_chain()
      
      log.info("Conversational RAG initialized", session_id = self.session_id)

    except Exception as e:
      log.error("Failed to initialize Conversational RAG", error = str(e))
      raise DocumentPortalException("Initialization error in Conversational RAG", sys)

  def load_retriever_from_faiss(self, index_path:str, k:int=5, index_name:str="index", search_type:str="mmr", fetch_k:int=20, lambda_mult:float=0.5, search_kwargs: Optional[Dict[str,Any]]=None):
    """
    Load FAISS vectorstore from disk and build retriever + LCEL chain
    """
    try:
      if not os.path.isdir(index_path):
        raise FileNotFoundError(f"FAISS index directory not found: {index_path}")
      embeddings = ModelLoader().load_embeddings()
      vectorestore = FAISS.load_local(index_path,embeddings,index_name=index_name,allow_dangerous_deserialization=True)

      if search_kwargs is None:
        search_kwargs = {"k":k}
        if search_type == "mmr":
          search_kwargs["fetch_k"] = fetch_k
          search_kwargs["lambda_mult"] = lambda_mult
      
      self.retriever = vectorestore.as_retriever(search_type=search_type, search_kwargs=search_kwargs)

      self._build_lcel_chain()

      log.info(
        "FAISS retriever loaded successfully", 
        index_path=index_path, 
        index_name=index_name, 
        k=k,
        session_id=self.session_id,
        search_type=search_type,
        fetch_k=fetch_k if search_type == "mmr" else None,
        lambda_mult=lambda_mult if search_type == "mmr" else None
      )
      return self.retriever
    
    except Exception as e:
      log.error("Failed to load FAISS retriever", error = str(e), index_path=index_path, index_name=index_name, k=k,session_id=self.session_id)
      raise DocumentPortalException("FAISS retriever loading error in Conversational RAG", sys)

  def invoke(self, user_input:str, chat_history: Optional[List[BaseMessage]] = None) -> str:
    """
    Invoke the LCEL pipeline.
    """
    try:
      if self.chain is None:
        raise DocumentPortalException("Conversational RAG chain is not initialized. Call load_retriever_from_faiss() before invoke().", sys)
      
      chat_history = chat_history or []
      payload = {"input":user_input, "chat_history": chat_history}
      answer = self.chain.invoke(payload)
      if not answer:
        log.warning("No answer generated", user_input=user_input, session_id=self.session_id)
        return "No answer generated."
      #Validate answer type and length using Pydantic model
      try:
        validated = ChatAnswer(answer=str(answer))
        answer = validated.answer
      except ValidationError as ve:
        log.error("Invalid chat answer", error=str(ve))
        raise DocumentPortalException("Invalid chat answer generated by LLM", sys)
      log.info("Chain invoked successfully", user_input=user_input, answer_preview=str(answer)[:150], session_id=self.session_id)
      return answer
    
    except Exception as e:
      log.error("Failed to invoke Conversational RAG", error = str(e), user_input=user_input, session_id=self.session_id)
      raise DocumentPortalException("Invocation error in Conversational RAG", sys)

  def _load_llm(self):
    try:
      llm = ModelLoader().load_llm()
      if not llm:
        raise ValueError("LLM could not be loaded")
      log.info("LLM loaded successfully", session_id = self.session_id)
      return llm
    except Exception as e:
      log.error("Failed to load LLM", error = str(e))
      raise DocumentPortalException("LLM loading error in Conversational RAG",sys)
  
  @staticmethod
  def _format_docs(docs) -> str:
    return "\n\n".join(getattr(d,"page_content",str(d)) for d in docs)
  
  def _build_lcel_chain(self):
    try:
      if self.retriever is None:
        raise DocumentPortalException("No retriever set before building LCEL chain", sys)
      
      #1) Rewrite user ques with chat history context (making a chain here)
      question_rewriter = (
        {"input": itemgetter("input"), "chat_history": itemgetter("chat_history")}
        | self.contextualize_prompt
        | self.llm
        | StrOutputParser()
      )

      #2) Retrieve docs for rewritten question
      retrieve_docs = question_rewriter | self.retriever | self._format_docs

      #3) Answer using retrieved context + original question + chat history
      self.chain = (
        {
          "context": retrieve_docs,
          "input": itemgetter("input"),
          "chat_history": itemgetter("chat_history")
        }
        | self.qa_prompt
        | self.llm
        | StrOutputParser()
      )

      log.info("LCEL graph built successfully", session_id = self.session_id)
    except Exception as e:
      log.error("Failed to build LCEL chain", error = str(e), session_id = self.session_id)
      raise DocumentPortalException("LCEL chain building error in Conversational RAG", sys)
